const fs=require('node:fs'),path=require('node:path');const {chromium}=require('/private/tmp/seo-audit-tools/node_modules/playwright');const root='/Users/zslepova/IvanOS/.worktrees/seo-finalize',out=root+'/audits/seo-20261009',reg=JSON.parse(fs.readFileSync(root+'/data/statyi.json')).statyi;
(async()=>{const b=await chromium.launch({channel:'chrome',headless:false,args:['--window-size=1470,956']});let results=[];try{
for(const width of [1470,390]){const ctx=await b.newContext({viewport:{width,height:width===1470?956:844},deviceScaleFactor:1,permissions:['clipboard-read','clipboard-write']});const p=await ctx.newPage();for(const slug of ['','politika',...reg.filter(x=>x.status==='live'&&!x.noindex_reason).map(x=>x.slug)]){const errors=[];const onError=e=>errors.push(e.message);p.on('pageerror',onError);const url='http://127.0.0.1:8771'+(slug===''?'/':slug==='politika'?'/politika/':'/claude-ai/'+slug+'/');await p.goto(url,{waitUntil:'load'});await p.evaluate(async()=>{for(let y=0;y<document.body.scrollHeight;y+=800){scrollTo(0,y);await new Promise(r=>setTimeout(r,40))}scrollTo(0,0);await Promise.race([Promise.all([...document.images].filter(i=>i.getAttribute('src')).map(i=>i.decode().catch(()=>{}))),new Promise(r=>setTimeout(r,3000))])});
const state=await p.evaluate(()=>({title:document.title,h1:document.querySelector('h1').textContent,overflow:document.documentElement.scrollWidth>innerWidth,wideElements:[...document.querySelectorAll('main *')].filter(e=>{let r=e.getBoundingClientRect();return r.width&&r.right>innerWidth+1&&getComputedStyle(e).position!=='fixed'}).slice(0,8).map(e=>e.tagName+'.'+e.className),brokenImages:[...document.images].filter(i=>i.getAttribute('src')&&i.complete&&!i.naturalWidth).map(i=>i.src),separateAnswer:!!document.querySelector('.quick-answer'),intro:(document.querySelector('.lead,.intro-lede')?.innerText||null)}));let interactions={};
const sample=['','pyat-skillov-claude-code','zakryt-sekrety-ot-claude-code','gotovye-fayly-excel-word-pdf','svoy-server-dlya-claude','shtat-agentov-paperclip','chatgpt-composio-prilozheniya','opus-55-protiv-gpt-6-astra','uley-agentov-ruflo','chetyre-mcp-claude-code','pyat-instrumentov-dlya-sayta'].includes(slug);
if(sample){await p.screenshot({path:path.join(out,'skriny','dovodka-'+(slug||'home')+'-'+width+'.png'),fullPage:true});const theme=p.locator('.theme-toggle');if(await theme.count()){const old=await p.locator('html').getAttribute('data-theme');await theme.click();interactions.theme=(await p.locator('html').getAttribute('data-theme'))!==old;await theme.click()};const toc=p.locator('.mobile-toc summary');if(width===390&&await toc.count()&&await toc.isVisible()){await toc.click();interactions.toc=await toc.evaluate(e=>e.parentElement.open);await toc.click()};const copy=p.locator('button[data-copy-target]').first();if(await copy.count()){await copy.click();await p.waitForTimeout(150);const expected=await copy.evaluate(e=>document.getElementById(e.dataset.copyTarget).textContent);interactions.copy=(await p.evaluate(()=>navigator.clipboard.readText()))===expected};const zoom=p.getByRole('button',{name:'Увеличить',exact:true}).first();if(await zoom.count()){await zoom.click();interactions.zoom=await p.locator('.viewer,dialog.image-viewer').first().evaluate(e=>e.hasAttribute('open')).catch(()=>false);await p.keyboard.press('Escape')};if(slug===''){const search=p.locator('input[type=search]');await search.fill('эволюция');interactions.search=await p.locator('.guide-link:visible').count();await search.fill('');const select=p.locator('select');console.log('SELECTS',await select.count());if(await select.count()){await select.first().selectOption('sravnenie');interactions.comparison=await p.locator('.guide-link:visible').count();await select.first().selectOption('all').catch(()=>{})}}
}
results.push({slug:slug||'home',width,url,...state,errors,interactions});fs.writeFileSync(path.join(out,'browser-dovodka.json'),JSON.stringify(results,null,2));if(state.overflow||state.brokenImages.length||errors.length||state.separateAnswer||Object.values(interactions).some(v=>v===false))throw Error('Browser regression: '+slug+' '+width);console.log(width,slug||'home','overflow',state.overflow,'broken',state.brokenImages.length,'errors',errors.length,JSON.stringify(interactions));p.off('pageerror',onError);
}await ctx.close()}
}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
