const fs=require('node:fs'),path=require('node:path');const {chromium}=require('/private/tmp/seo-audit-tools/node_modules/playwright');
const out='/Users/zslepova/IvanOS/.worktrees/seo-finalize/audits/seo-20261009';const vitals=fs.readFileSync('/private/tmp/seo-audit-tools/node_modules/web-vitals/dist/web-vitals.iife.js','utf8');
(async()=>{const b=await chromium.launch({channel:'chrome',headless:false,args:['--window-size=1470,956']});const results=[];try{for(const [stage,base] of [['before','http://127.0.0.1:8772'],['after','http://127.0.0.1:8771']])for(const slug of ['','pyat-skillov-claude-code','chatgpt-composio-prilozheniya','opus-55-protiv-gpt-6-astra'])for(let run=1;run<=3;run++){
const ctx=await b.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1,permissions:['clipboard-read','clipboard-write']});const p=await ctx.newPage();const metrics={},errors=[],interactions=[];p.on('pageerror',e=>errors.push(e.message));await p.exposeFunction('collectVital',m=>{metrics[m.name]={value:m.value,rating:m.rating}});await p.addInitScript({content:vitals+`;for(const n of ['LCP','CLS','INP'])webVitals['on'+n](m=>window.collectVital({name:m.name,value:m.value,rating:m.rating}),{reportAllChanges:true});`});
const cdp=await ctx.newCDPSession(p);await cdp.send('Network.enable');await cdp.send('Network.setCacheDisabled',{cacheDisabled:true});await cdp.send('Network.emulateNetworkConditions',{offline:false,latency:150,downloadThroughput:1600000/8,uploadThroughput:750000/8,connectionType:'cellular4g'});await cdp.send('Emulation.setCPUThrottlingRate',{rate:4});
const url=base+(slug?'/claude-ai/'+slug+'/':'/');await p.goto(url,{waitUntil:'load',timeout:90000});await p.waitForTimeout(2500);
for(const s of ['#cookie-decline','.theme-toggle','.mobile-toc summary','button[data-copy-target]']){const l=p.locator(s).first();if(await l.count()&&await l.isVisible()){await l.click();interactions.push(s);await p.waitForTimeout(400);if(s==='.theme-toggle'||s==='.mobile-toc summary'){await l.click();await p.waitForTimeout(300)}}}
if(!slug){await p.locator('input[type=search]').fill('эволюция');await p.waitForTimeout(600);await p.locator('input[type=search]').fill('');interactions.push('search')}
const state=await p.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,brokenImages:[...document.images].filter(x=>x.getAttribute('src')&&x.complete&&!x.naturalWidth).map(x=>x.src)}));await p.goto('about:blank');await p.waitForTimeout(500);
const result={stage,slug:slug||'home',run,url,browser:b.version(),conditions:{viewport:'390x844',CPU_slowdown:4,latency_ms:150,download_bps:1600000,upload_bps:750000,cache:'cold',library:'web-vitals 6.2.3'},metrics,interactions,errors,...state,limitation:'Laboratory scripted interactions; not field p75. Missing metric is null, never zero.'};for(const n of ['LCP','CLS','INP'])if(!result.metrics[n])result.metrics[n]=null;results.push(result);fs.writeFileSync(path.join(out,'cwv-current.json'),JSON.stringify(results,null,2));console.log(stage,slug||'home',run,JSON.stringify(metrics));await ctx.close();
}}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
