from pathlib import Path
import json,subprocess,html
import statistics
from bs4 import BeautifulSoup
root=Path.cwd();reg=json.loads((root/'data/statyi.json').read_text())['statyi'];meta=json.loads((root/'data/seo.json').read_text());rows=[];changed=0
priority=['chatgpt-composio-prilozheniya','opus-55-protiv-gpt-6-astra','uley-agentov-ruflo','chetyre-mcp-claude-code','pyat-instrumentov-dlya-sayta']
for r in sorted(reg,key=lambda r:(priority.index(r['slug']) if r['slug'] in priority else 100,r['slug'])):
 rel='claude-ai/'+r['slug']+'/index.html';old=BeautifulSoup(subprocess.check_output(['git','show','2b5a5e2:'+rel],text=True),'html.parser');new=BeautifulSoup((root/rel).read_text(),'html.parser');titles=[s.title.get_text() for s in [old,new]];heads=[s.h1.get_text(' ',strip=True) for s in [old,new]];diff=titles[0]!=titles[1];changed+=diff
 def introduction(soup):
  ps=list(soup.h1.find_all_next('p'));p=next((p for p in ps if set(p.get('class',[]))&{'lead','intro-lede'}),None)
  if p is None:p=next(p for p in ps if not set(p.get('class',[]))&{'uroven-metka','meta','sun-caption'})
  return p.get_text(' ',strip=True)
 before_answer=introduction(old)
 answer=introduction(new);additional=[]
 for mark in ['seo-related','seo-faq']:
  if new.select_one('.'+mark):additional.append(new.select_one('.'+mark).get_text(' ',strip=True))
 old_headers=[x.get_text(' ',strip=True) for x in old.find_all(['h1','h2'])];new_headers=[x.get_text(' ',strip=True) for x in new.find_all(['h1','h2']) if not x.find_parent(class_=['seo-related','seo-faq'])]
 extra=('<p><b>Изменение заголовков разделов:</b> '+html.escape(' | '.join(old_headers))+' → '+html.escape(' | '.join(new_headers))+'</p>') if old_headers!=new_headers else ''
 if additional:extra+='<p><b>Дополнения внизу статьи:</b> '+html.escape(' | '.join(additional))+'</p>'
 row=f'''<details class="entry" {'open' if r['slug'] in priority else ''}><summary><span>{html.escape(r['title'])}</span><small>{html.escape(r.get('kod_slovo',''))} · {'title изменён' if diff else 'title сохранён'}</small></summary><div class="columns"><section><span class="label">Было · main 2b5a5e2</span><p class="field">Title вкладки / поиска</p><h3>{html.escape(titles[0])}</h3><p class="field">Заголовок статьи</p><h2>{html.escape(heads[0])}</h2><p class="field">Исходное вступление</p><p>{html.escape(before_answer)}</p><a href="http://127.0.0.1:8772/{rel.removesuffix('index.html')}" target="_blank">Открыть исходную статью ↗</a></section><section class="after"><span class="label">Стало · SEO-превью</span><p class="field">Title вкладки / поиска</p><h3>{html.escape(titles[1])}</h3><p class="field">Заголовок статьи</p><h2>{html.escape(heads[1])}</h2><p class="field">Единственное вступление · {len(answer.split())} слов</p><p class="answer">{html.escape(answer)}</p><a href="/{rel.removesuffix('index.html')}" target="_blank">Открыть статью с SEO ↗</a></section></div>{'<details class="extra"><summary>Другие видимые SEO-изменения</summary>'+extra+'</details>' if extra else ''}</details>'''
 rows.append(row)
css='''*{box-sizing:border-box}body{margin:0;background:#f4f3ed;color:#163837;font:17px/1.65 -apple-system,BlinkMacSystemFont,Arial,sans-serif}header,main{max-width:1280px;margin:auto;padding:36px 28px}header{padding-bottom:20px}h1{font-size:clamp(28px,5vw,52px);line-height:1.1;margin:12px 0 20px}h2{font-size:26px;line-height:1.25}h3{font-size:20px;line-height:1.4}a{color:#146761;text-underline-offset:4px}input{width:100%;max-width:650px;padding:14px;border:1px solid #78938c;border-radius:8px;font:inherit;background:white}.entry{background:white;border:1px solid #c8d6cc;border-radius:12px;margin-bottom:18px;overflow:hidden}.entry>summary{cursor:pointer;padding:20px 24px;font-weight:700;background:#e7eee8;display:flex;gap:16px;justify-content:space-between}.entry small{font-size:13px;white-space:nowrap;font-weight:400}.columns{display:grid;grid-template-columns:1fr 1fr}.columns section{padding:22px 28px;min-width:0}.after{background:#eff6ef;border-left:1px solid #ccdccc}.field{color:#657d74;font-size:13px;margin:24px 0 6px}.label{font-size:14px;letter-spacing:.02em;font-weight:750}.answer{border-left:4px solid #629980;padding-left:16px}.extra{padding:16px 28px;font-size:14px;border-top:1px solid #ccdccc}.extra summary{cursor:pointer}.note{border:1px solid #91aaa0;background:#e7eee8;border-radius:12px;padding:16px 20px}.badge{display:inline-block;font-size:13px;font-weight:800;letter-spacing:.06em;color:#ba4e25}.muted{color:#577068}footer{max-width:1280px;margin:auto;padding:28px}.hidden{display:none}@media(max-width:700px){header,main{padding:24px 14px}.columns{grid-template-columns:1fr}.columns section{padding:18px}.after{border-left:0;border-top:1px solid #ccdccc}.entry>summary{padding:16px;display:block}.entry small{display:block;margin-top:6px}h2{font-size:24px}}'''
vitals=json.loads((root/'audits/seo-20261009/cwv-dovodka.json').read_text());before_lcp=statistics.median(x['metrics']['LCP']['value'] for x in vitals if x['stage']=='before');after_lcp=statistics.median(x['metrics']['LCP']['value'] for x in vitals if x['stage']=='after');after_cls=statistics.median(x['metrics']['CLS']['value'] for x in vitals if x['stage']=='after')
page=f'''<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>SEO: было / стало · Про новое</title><style>{css}</style></head><body><header><span class="badge">ПРЕВЬЮ · НЕ ОПУБЛИКОВАНО</span><h1>Что увидит читатель после SEO-правок</h1><p>Все {len(rows)} статей на одной странице. Слева свежий main, справа версия для согласования: title вкладки и поиска, заголовок статьи и единственное вступление под ним</p><p class="muted">Изменено {changed} title · 27 вступлений доведены до 40-60 слов, 23 сохранены · исходная база 09.10.2026, коммит 2b5a5e2</p><p class="note">Главная на телефоне: LCP {before_lcp} → {after_lcp} мс · CLS 0,109 → {after_cls:g}. Медиана трёх лабораторных замеров Chrome, 390x844, 4G и CPU x4</p><div class="note">Раскрой статью и сравни текст. Пять новых материалов раскрыты сразу. Отдельный быстрый ответ убран из всех 50 статей. Сохранилась первая фраза исходного вступления; короткие вступления дополнены, длинные сокращены до 40-60 слов. Canonical, JSON-LD и lastmod в текст статьи не выводятся. Дополнительные ссылки, вопросы и изменения заголовков разделов показаны под сравнением. У МОНТАЖА и копии Higgsfield исправлены размеры плеера и контейнеров скриншотов на телефоне</div><p><input id="search" type="search" placeholder="Найти по названию или кодовому слову" aria-label="Найти статью"></p><p><a href="/">Открыть главную SEO-превью ↗</a> · <a href="./dovodka-report.md">Отчёт о доводке</a></p></header><main>{''.join(rows)}</main><footer>Публикация только после ОК Жанны · Сборка блокирует live-статью без SEO-данных · Даты lastmod закреплены в реестре и не меняются при пересборке</footer><script>document.querySelector('#search').addEventListener('input',e=>{{const q=e.target.value.toLocaleLowerCase('ru');document.querySelectorAll('.entry').forEach(x=>x.classList.toggle('hidden',!x.querySelector('summary').textContent.toLocaleLowerCase('ru').includes(q)))}});</script></body></html>'''
(root/'audits/seo-20261009/preview.html').write_text(page)
print('Preview:',len(rows),'articles;',changed,'changed titles')
